### ISSUE TITLE
Инструкции по сборке

### ISSUE THREAD

**Issue by noteMASTER11** [Mitradis/SkyrimLauncher#1]
Прошу добавить в [Readme.md](https://github.com/Mitradis/SLMPLauncher/blob/main/README.md) краткие инструкции по сборке из исходников.

Как я понял, если весь проект писан на C#, необходим свежий Visual Studio и как минимум установленные в ОС Windows средства сборки.

Верно ли понимаю, что можно следовать этому гайду Microsoft? https://docs.microsoft.com/en-us/visualstudio/get-started/tutorial-open-project-from-repo?view=vs-2022

**Comment by Mitradis** [comment]
Запустить [SLMPLauncher.sln](https://github.com/Mitradis/SLMPLauncher/blob/main/SLMPLauncher.sln) - собрать решение.
